chore: temp commit40

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -55,22 +55,22 @@ jobs:
             rm -rf ./chapanda-website-service || true
             git clone  "https://x-access-token:$GH_TOKEN@github.com/baiwusanyu-c/chapanda-website-service.git"
             cd ./chapanda-website-service 
-            pnpm install
-            pnpm run build
-            mkdir -p dist/env
-            echo 'MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD' >> dist/env/.env
-            echo 'MYSQL_ROOT_USER=$MYSQL_ROOT_USER' >> dist/env/.env
-            echo 'MYSQL_SERVER_HOST=$MYSQL_SERVER_HOST' >> dist/env/.env
-            echo 'REDIS_SERVER_HOST=$REDIS_SERVER_HOST' >> dist/env/.env
-            echo 'REDIS_ROOT_PASSWORD=$REDIS_ROOT_PASSWORD' >> dist/env/.env
-            echo 'MINIO_SERVER_HOST=$MINIO_SERVER_HOST' >> dist/env/.env
-            echo 'MINIO_SERVER_ACCESS=$MINIO_SERVER_ACCESS' >> dist/env/.env
-            echo 'MINIO_SERVER_SECRET=$MINIO_SERVER_SECRET' >> dist/env/.env
-            echo 'MINIO_SERVER_BUKET=$MINIO_SERVER_BUKET' >> dist/env/.env
-            if [ ! -f dist/env/.env ]; then
-              echo '::error::.env 文件未生成'
-              exit 1
-            fi
+            # pnpm install
+            # pnpm run build
+            # mkdir -p dist/env
+            # echo 'MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD' >> dist/env/.env
+            # echo 'MYSQL_ROOT_USER=$MYSQL_ROOT_USER' >> dist/env/.env
+            # echo 'MYSQL_SERVER_HOST=$MYSQL_SERVER_HOST' >> dist/env/.env
+            # echo 'REDIS_SERVER_HOST=$REDIS_SERVER_HOST' >> dist/env/.env
+            # echo 'REDIS_ROOT_PASSWORD=$REDIS_ROOT_PASSWORD' >> dist/env/.env
+            # echo 'MINIO_SERVER_HOST=$MINIO_SERVER_HOST' >> dist/env/.env
+            # echo 'MINIO_SERVER_ACCESS=$MINIO_SERVER_ACCESS' >> dist/env/.env
+            # echo 'MINIO_SERVER_SECRET=$MINIO_SERVER_SECRET' >> dist/env/.env
+            # echo 'MINIO_SERVER_BUKET=$MINIO_SERVER_BUKET' >> dist/env/.env
+            # if [ ! -f dist/env/.env ]; then
+            #   echo '::error::.env 文件未生成'
+            #   exit 1
+            # fi
             export MYSQL_ROOT_PASSWORD='$MYSQL_ROOT_PASSWORD'
             export REDIS_ROOT_PASSWORD='$REDIS_ROOT_PASSWORD'
             export MINIO_ROOT_USER='$MINIO_ROOT_USER'
